# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0003_auto_20191021_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebook_art',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
