# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-22 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0004_gamebook_art_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gamebook_art',
            name='image',
        ),
        migrations.AddField(
            model_name='carousel',
            name='banners',
            field=models.ImageField(default='', upload_to='carousel_banners'),
        ),
        migrations.AddField(
            model_name='gamebook_art',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='content_thumbnails'),
        ),
    ]
