# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0006_auto_20191027_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebook_art',
            name='image1',
            field=models.ImageField(default='', upload_to='Screenshoot'),
        ),
        migrations.AddField(
            model_name='gamebook_art',
            name='image2',
            field=models.ImageField(default='', upload_to='Screenshoot'),
        ),
        migrations.AddField(
            model_name='gamebook_art',
            name='image3',
            field=models.ImageField(default='', upload_to='Screenshoot'),
        ),
        migrations.AddField(
            model_name='gamebook_art',
            name='image4',
            field=models.ImageField(default='', upload_to='Screenshoot'),
        ),
        migrations.AddField(
            model_name='gamebook_art',
            name='image5',
            field=models.ImageField(default='', upload_to='Screenshoot'),
        ),
    ]
