# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0007_auto_20191031_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamebook_art',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='gamebook_art',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='gamebook_art',
            name='image5',
        ),
    ]
