# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0008_auto_20191031_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebook_art',
            name='min_req',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gamebook_art',
            name='rec_req',
            field=models.TextField(default=''),
        ),
    ]
