# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0010_remove_gamebook_art_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebook_art',
            name='Gdrive1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='gamebook_art',
            name='Gdrive2',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='gamebook_art',
            name='Video_url',
            field=models.URLField(default=''),
        ),
    ]
