# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0011_auto_20191031_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebook_art',
            name='Gdrive1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='Gdrive2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='Video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
