# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-03 09:43
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0012_auto_20191102_2253'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gamebook_art',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
