# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-03 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0013_auto_20191103_1743'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gamebook_art',
            managers=[
            ],
        ),
    ]
