# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0015_auto_20191218_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='banners',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='title',
        ),
        migrations.AddField(
            model_name='carousel',
            name='ans',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='carousel',
            name='faq',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='carousel',
            name='num',
            field=models.CharField(default='', max_length=255),
        ),
    ]
