# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 17:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0016_auto_20200126_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='ans',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='min_req',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='rec_req',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
