# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0017_auto_20200127_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='ans',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='min_req',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='rec_req',
            field=models.TextField(default=''),
        ),
    ]
