# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0019_auto_20200127_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebook_art',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
