# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 17:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0021_auto_20200127_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebook_art',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
