# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 18:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0022_auto_20200127_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebook_art',
            name='body',
            field=ckeditor.fields.RichTextField(default='type'),
        ),
        migrations.AlterField(
            model_name='gamebook_art',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
