# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 19:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0025_auto_20200127_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebook_art',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
