# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0027_auto_20200127_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebook_art',
            name='body',
            field=models.TextField(),
        ),
    ]
