# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0030_auto_20200128_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebook_art',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
