# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 19:11
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0031_auto_20200128_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='ans',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
