# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-29 08:16
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook_art', '0032_auto_20200128_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='ans',
            field=tinymce.models.HTMLField(),
        ),
    ]
